{% set name = "elfx86exts" %}
{% set version = "0.6.1" %}
{% set sha256 = "ddaa3d9cabb91fb45999fbfb219bf67aec2da6687273b6a908ae66e4eeb6b15a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://crates.io/api/v1/crates/{{ name }}/{{ version }}/download
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - rust

test:
  commands:
    - elfx86exts $PREFIX/bin/elfx86exts

about:
  home: https://crates.io/crates/elfx86exts
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Disassemble an ELF binary containing x86 instructions and print out which extensions it uses.
  doc_url: https://docs.rs/elfx86exts/
  dev_url: https://github.com/pkgw/elfx86exts

extra:
  recipe-maintainers:
    - pkgw
