travis:
  secure:
    BINSTAR_TOKEN: R6GkatSw4PD4LVfEoRLvd+Jh/9JQ9EIBnAf3w8bM4o2hiTuMC0tRfCARMuzEtVzivDr/KWU0/+xEFGQa1FxmTvNXXNU6z6o45LIiI+fDpxHGDJP7wsrQ4gLmj9vJfwV76xzsdSO0z5G66ZF3YShlESRiNmnPUXATLn7XlyW0kc2Gwd21ZmRvRomse4AeV9JJtCBZ3V2+q984JOQrJQ0MA/DH+QK8G6pQ+4660t9eHUJBrYzUqthRWbM+IXErhe2ZxzHuLB/ZLvABBRZHe6w26xjyLB36NXyIUNIvMj9ZTj93BR1B3bXnI2zSj21ND/HFZApged1mZuRcHhwFBRu6Ox0RlfeRBnWKVWWedFi7rleiDv20IbsxWot87B0+3n3/VwGxxuTHYNH469Bl+lvXWrl+xLrsIiYsz1W1FtQLHYHewgpym7Q6gBH+cGziiFjzKXCFHYdUKslcpHCJeGdmHSgW/Nl1Pvv5dUyD7K4MVsQ922e7iCrPQsk8HSEb3b2espH55rIHbqY2SDBqoeife5U4dx++00MnSSOQFxvBbGnlZpp6nUvL2jVzezKsAaLkIgpCDKi6jaiUm3ff258J8sXnvbGYw4s4ZUoiYnJOZWXHo+SX2zbs/I+TxEgsw4hh6squzyZIR142YwZuN88UFNrizQs+XLs131PcgwzDEWY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
