travis:
  secure:
    BINSTAR_TOKEN: vRr73HCIPfx6jO1d+u2jKnVv8xia4bIFafnIyQWrC+krBGlyiNLwlBX2nqSlSaCewzJ4mWcGl+yAPFZ0YxsKW6wAoXNSQ5XvzPA9mt5EVQ608vnezjJT1+VVPwtadM/TbQqo1Ozro8SRDarSZq0NPXwe/CV/wiaidkzEPL/CEQo3B0DUnBPEbSKDzpZvseTWv9Zn7pLgHr/DGrT+sEppNc6Qv89wCn18PgOONDcJSIRHz2OMLq/V4BLX6ckF2/sKzfbq63IpUlcdowVrYcjOzA5O3jsHYSNlcrnH6FfN+AgPpFObyd7zI2W8+xdbQ8By4h+Jff9fOZYZf36zTDKdRF08QpZ8pyxg4XTvTFVe609XDEl/blfBCePSVNQDv/q0emWL42GNB5LXcAg64+bbBJgRQTO/yfboQIadrove/M5bwz4MdCrSryjIUcOvHyCBr1kXNKIaVpD+jWgOuJE0kIKabac952s3FM1UEJ5lJLkVN/9eD0OAsMwqjLD4oQHKZJ+zYWKyd5A6HXH0KtLItnLtW6G1mbQ3lxxf35lmkp3ZFxNGzQaRNvbXW+PNg1coAXkGUN0y5yLhEjYzkg32Q18gP18shuhFmYm3Q9m4O0GiTzZ3dUUHUbDtGzNKPxsygDRERNP4ozAde+WwmpiVd56+Pp/Y6YEKmapOw3nr70E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
